### ISSUE TITLE
Pre Turkey Status

### ISSUE THREAD

**Issue by jm1021** [nighthawkcoders/flocker_frontend#239]
@channel I will be going out on Jury Duty tomorrow.  This could extend till Friday.  

I expect every team to provided me planning status .   

Below is illustrative example.  You could build on existing idea.  People should have jobs and code responsibilities, be as specific as possible.
----

1st and foremost you need to discuss Sprint 4 objectives as a team... https://nighthawkcoders.github.io/portfolio_2025/csp/sprint3/objectives.  Only after this discussion could you make a report to me.

Then you need to do an outline on your product and features.  Below is something that is illustrative.

Team Lemonade-out-of-Lemons
Our project recognizes need for blogging and user database.  Using these two elements we have decided to build a business site for our Lemonade stand.

GitHub IO link is working: https://jm1021.github.io/john_2025/
Frontend repo: https://github.com/nighthawkcoders/flocker_frontend
Backend repo: https://github.com/nighthawkcoders/flocker_backend

Home Page will be focused on Lemonade Sale, we will ask user to login and sign up before they buy.
Profile adjustments, we will ask them for their Venmo information so we can request billing to their account.
Product information and blogging.
Inventory and Accounting

Trio 1 / Home Page, User Profile, API Request to Venmo
John Mortensen (assistant scrum master), https://github.com/jm1021/john_2025
Integration and Branching strategy, APIs and Database changes
Pretend  Student (scrummer #1), https://github.com/nighthawkcoders/student_2025
Home Page of Site and design, JavaScript code to update user profile and order updates
Pretend Student (scrummer #2), ...
APIs and Database for orders.  User blogging and satisfaction on products.

Trio 2 / Product Page
Pretend Person  (scrum master)
Kanban Board, backend SQLalchemy data definition and initialization
Pretend Person  (scrummer #3)
API's and methods for Adding Products, Administrative UI to support product adds, inventory updates. 
Pretend Person (scrummer #4)
Figma Designs for site, API's and methods.  API's and methods to show Sale History, Administrative UI to show sales.

Next Steps
- [-] To-do 1
- [-] To-do 2

**Comment by prajnar123123213** [comment]
https://github.com/arshiadebroy/flocker_frontend/issues/1#issue-2676887360

**Comment by code259** [comment]
**Team Pawnly**
- Our project will be a social media website and forum where users can discuss chess topics and interact with Artificial Intelligence to learn and play chess.
- Our project is based on the flocker project and will utilize numerous elements such as the posting and post database, user authentication and database, and external APIs pertaining to chess. For the posts specifically, we will require an upload system that will be based on the pfp storage system, and we will likely need to create a new API endpoint for the storage system. 
- Our initial discussion for Sprint 4: https://github.com/code259/sprint4_frontend/issues/1#issue-2677335072

**Pages**
- Landing Page: Since page will be a social media website, we will have landing page to inform new visitors of the purpose of the website and to redirect to various pages.
- Home Page: After login and authentication the user will go to a home page with a list of posts by all users, of chess related topics such as certain board positions, tactics, questions, etc. User will be able to view the post and interact with the posts by having commenting capabilities, which will likely be shown in a modal. 
- Chat Page: Will have a chess board where users can interact with an Gemini or other LLM to talk and learn about chess.
- Game Page (TBD): May create a page where user can use a real chess board to play against a bot, plan on using some sort of API. 

**Tasks & Roles**
Note: Groups not finalized until Add/Drop deadline. 
- Scrum Master: Nikhil Maturi
- Assistant Scrum Master: Aarush Gowda
- Developer 1: Vasanth Rajasekaran
   - Landing Page Design and Development, Javascript for Animations (GSAP)
- Developer 2: Aarush Gowda 
   - Landing Page Design and Development, UML, and Javascript for Modal Design
- Developer 3: Nikhil Maturi
   - API Calls and Upload API
- Developer 4: TBD

**Next Steps (For Checkpoint 1):**
List of future ideas: https://github.com/code259/sprint4_frontend/issues/2#issue-2677357558
- [x] Create Kanban Board to track iterations and features. 
- [ ] Utilize PEP 8 Guideline for Code (https://peps.python.org/pep-0008/#introduction)
- [ ] Use UML or planning methods to show plan for integration of new ideas and features from Flocker.
- [x] Create visually appealing Homepage - create brief design using figma
- [ ] Remove redundancy in other pages and create good UX.
- [ ] Remove features from Flocker not required for our project.
- [ ] Implement API requests to LLM (AI Model), sending image data.

**Comment by XavierTho** [comment]
## Cantella
Combining utility, user databases, & personal interest, our final project is a social-like site for academic purposes, where individuals can collaboratively study and keep up with classes that are exclusively DNHS based.

Repositories:
- https://github.com/XavierTho/cantella_frontend
- https://github.com/XavierTho/cantella_backend

### Team Layout
#### Trio 1 / [Structural Design, Flashcards, & Quiz Implementation]
- Scrum Master: Xavier T 
  *Responsible for the site's foundational structure and overall coordination.*  
- Developer 1: Armaghan Z 
  *Focus on implementing dynamic and customizable flashcards.* 
- Developer 2: Zafeer A 
  *Tasked with building an interactive quiz system.*  

#### Trio 2 [Login Page, User Info]
- Assistant Scrum Master: Nolan Y
  *Oversees and develops the login interface for user authentication.*  
- Developer 3: Jackson P 
  *Handles fetching and displaying personalized user data.* 
- Developer 4: Arush S 
  *Ensures storing of user data.* 

### Main Ideas (currently)
- Flashcards
- Quiz-Maker
- Leaderboard
- Contributor system to classes (something like Wikipedia)
- Study material shared to everyone
- Free discussion (Q&A)

Next Steps:
- [ ] Adding preliminary classes for integration (AP Chem & AP World as of now)
- [ ] Setting up the 'theme' of the website
- [ ] Setting up user database

**Comment by blackstar3092** [comment]
# Project Frostbyte

## Project Overview:
This project develops a social media site follow the process outlined below:
1. Take a personality test that assigns a national park to the user based on their personality
2. Receive camping tips for the assigned location with chatroom feature for discussion
3. Navigate to national park home page where user's assigned national park is displayed
4. Rate and review the national park assigned (after the user goes to the park)

## Additional Features:
- Gemini integration in both elements (camping and traveling) with tips randomly generated

### Moderator Rules:
- Be kind and respectful of every person on this forum
- Be polite while commenting. Inappropriate or mean comments will be removed
- Use Gemini responsibly and only for travel purposes
- Most importantly, have fun while sharing your opinion!

## Links & Page Breakdown:
Frontend repo: https://github.com/blackstar3092/frostbyte_frontend
Backend repo: https://github.com/blackstar3092/frostbyte_backend

Home Page: focused on camping and personality-based national park assignment, where we will ask user to login to store their assigned national park.

Followed by: 
- Camping information and blogging.
- National park information and blogging

## Trio Divisions

### Trio 1: National Park Page and Chatroom

| **Name**       | **Github Page Link**    | **Assignments** |
|----------------|--------------------------------------|----------------------------------------|
| Risha Guha (scrum master) | https://blackstar3092.github.io/risha_guha_2025_1/ | Individual page styling (x2), Gemini integration and random prompt generator, integration with camping backend |
| Shriya Paladugu |  https://shriya1401.github.io/shriyap_2025/ | Individual page styling (x2), rate selection and storing in backend | 
| Ava Shalon | https://ava-dn.github.io/avas_2025/ | Home page styling, storing reviews in backend |

### Trio 2: Camping Page and Chatroom

| **Name**       | **Github Page Link**    | **Assignments** |
|----------------|--------------------------------------|----------------------------------------|
| Aranya Bhattacharya (assistant scrum master) |https://github.com/Mom5MoreMins/aranya_student_2025 | Backend for personality quiz, chat room (group contribution) 
| Abby Manalo |  https://abbymanalo.github.io/abby2025/ | Frontend for personality quiz, chat room (group contribution) | 
| Elliot Yang | https://github.com/Ellioty15/Elliot_2025 | Gemni integration, chat room (group contribution) |

## Design Layouts and UX: Found on our team's **[issue](https://github.com/blackstar3092/frostbyte_frontend/issues/1#issue-2680204398)**

Next Steps

- [ ]  Develop frontend pages: Personality tests for camping page and dropdown menus for national park selection
- [ ]  Integrate backend: Write script for personality test and store national park assignment in backend databases
- [ ]  Continue frontend development with new backend functionality

**Comment by vibha1019** [comment]
# Gift Recommendation Chatbot

## **Overview**
Create a chatbot feature that generates personalized gift recommendations based on user-inputted data and number of likes and reviews. 

Frontend repo: https://github.com/vibha1019/socialmedia_frontend
Backend repo: https://github.com/vibha1019/socialmedia_backend

### **Key Features**
1. **Gift Uploads by Category**  
   Users can upload holiday gift ideas categorized by recipient type:  
   - Teenage girl  
   - Teenage boy  
   - Mom  
   - Dad  
   - Grandma  
   - Grandpa  
   - Wife  
   - Husband   

2. **Engagement**  
   - Gift suggestions are ranked  based on the number of *likes* on uploaded posts.  
   - Include **reviews** from users who have tried or purchased the gift so they are more reliable.  

3. **Chatbot Functionality**  
   - Generates gift suggestions by analyzing:  
     - Recipient type  (detailed above)
     - Number of likes and reviews
   - Provides recommendations ( "This gift is highly rated for teenage girls!")  

---

## **Implementation Steps**


### **Trio 1**

| **Name**          | **Role**        | **GitHub Link**                                      | **Assignment**                                                                                                                                                       |
|-------------------|-----------------|------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Vibha Mandayam    | Scrum Master    | [GitHub Link](https://github.com/vibha1019/vibha_mandayam)                                     | - **Database Setup** <br> - Create a table for uploaded gift ideas with fields like `id`, `category`, `name`, `likes`, `reviews` <br> - Track user-generated likes. |
| Soni Dhenuva      | Scrummer #1      | [GitHub Link](https://github.com/SoniDhenuva/soni_2025)                                     | - **AI Model for Gift Recommendations** <br> - Integrate a AI chatbot to analyze t data he<br> - Use filtering algorithms for ranking. |


### **Trio 2**

| **Name**          | **Role**        | **GitHub Link**                                      | **Assignment**                                                                                                                                           |
|-------------------|-----------------|------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| Nora Ahadian      | Assistant Scrum Master     | [GitHub Link](https://github.com/NoraTheTurtle/nora_25)                                     | - Allow users to upload gift ideas with images, descriptions, and assign them to a recipient category. <br> - Include a *like* button and review section.  |
| Kushi Gade        | Scrummer #2     |  [GitHub Link](https://github.com/kushi236/kushig)                                        | - Function to change background, Putting descriptions for each product, Work on sidebar                                                                                                                          |
| Spencer Lyons     | Scrummer #3     | [GitHub Link]()                                     | - **Chatbot Interface** <br> - Interactive UI for users to enter recipient details (e.g., "Looking for a gift for my cousin") <br> - Display recommendations. |

---
## **User Flow**

1. **User Uploads Gift Idea**  
   - Navigate to the "Upload Gift" section.  
   - Fill out details: category, description, and optional photo.  
   - Gift becomes visible in its category feed.  

2. **Likes & Reviews**  
   - Users like and review other gift ideas.  
 
3. **Chatbot Interaction**  
   - User interacts with the chatbot, "What’s a good gift for my mom?"  
   - Chatbot generates a ranked list of gifts using likes, reviews, and user input.  

---
### Next Steps

- [ ] Finalize the database in order to store gift ideas, likes, and reviews.
- [ ] Create  the gift upload feature, which incluedes the ability to assign a recipient category, add descriptions, and upload images.
- [ ] Have a "like" button and ensure likes are saved and displayed correctly.
- [ ] Set up a review section for user feedback on gifts.
- [ ] Integrate a chatbot for collecting user input about recipient details.
- [ ] Design and include a recommendation engine to rank gift ideas based on likes and reviews.

**Comment by gabrielac07** [comment]
### Team Bookworms
Our team wants to facilitate book lovers and give them a platform where users can rate and talk about books. We will sort books and their discussions by genre so that users can easily find books they are interested in.

Frontend Repo: https://github.com/gabrielac07/sprint4_frontend
Backend Repo: https://github.com/gabrielac07/sprint4_backend

### Pages
**Landing Page:** Since the page will be a social media website, we will have a landing page to inform new visitors of the purpose of the website, show off all the genres, and tell them to log in.
**Home Page:** After login and authentication the user will go to a home page with a list of top book picks of the month and a search bar to look for books
**Chat Page:** Will have a chat page with multiple channels organized by genre where users can interact with a Gemini or other LLM to talk and learn about their favorite books and recommendations. 
**Reviews:** Once you find a book through a genre, you can give it a rating out of 5 stars.
**Try?:** Have a “Your next big read” page, embed an api and have it generate a book based on a certain genre. 
**Also try?:** User profile, they can add all the books they’ve read and stuff. 


### Trio 1 / Home Page, Profile/Preferences Page, Reviews page, Chat page
[Gabriela Connelly](https://gabrielac07.github.io/gabi_2025/)  (scrum master)
Kanban Board, profile page, something else
[Katherine Chen](https://github.com/kchen8478/katherine_2025) (scrummer 1)
Home Page of Site and design, JavaScript code to update user profile
[Aditi Bandaru](https://github.com/bagel-muncher/aditi_bandaru_csp_2025) (scrummer 2)
APIs and Database for orders.  User blogging and satisfaction on books.

### Trio 2 / Database Schema, Initialization, Backup, Restore, Gemini Integration Feature
[Avika Prasad](https://github.com/avikaprasad22/avika_2025) (assistant scrum master)
Branching strategy, APIs and Database changes
[Maryam Abdul-Aziz](https://github.com/MaryamAbdul-Aziz/maryam_2025)  (Integrator)
Integration, API's and methods for adding books, Administrative UI to support book adds.
[Soumini Kandula](https://github.com/Soumini97/soumini_2025) (scrummer 4)
Figma Designs for site, API's and methods.  API's and methods to show book/user history

### Next Steps (To-do list) 😃😡

- [ ] Create Kanban board
- [ ] Design login page, home page, profile page, chat page, reviews page in UI design site (Figma, etc.)
- [ ] Code frontend of page (landing page, review page, genre pages, etc.)
- [ ] Create channels for backend
- [ ] Put data in backend channels
- [ ] Connect frontend and backend

**Comment by Ahaanv19** [comment]
# Book Reviewing and Discussion Database
# Lit Connect

Our project allows users to interact with various books, rate them out of 5 stars, and have discussions with other young scholars in a chat box. The purpose is to understand different perspectives on books.

### Repositories
- **Frontend:** [sprint4_flocker_frontend](https://github.com/Ahaanv19/sprint4_flocker_frontend)
- **Backend:** [sprint4_flocker_backend](https://github.com/Ahaanv19/sprint4_flocker_backend)

### Features
- **Home Page:** Prompts users to log in before they can access the book reviewing and discussion features.
- **User Profile Adjustments:** Users can customize profile details, including password, username, name, profile picture, and screen name.
- **Book Reviews:** Users can view summaries and rate books up for review.
- **Chat Room:** Provides a discussion space for readers to share opinions on books and engage with others.

## Team Roles and Responsibilities

### Trio 1 - Home Page, User Profile
- **Ahaan Vaidyanathan (Scrum Master)**
  - Main page layout
  - Blogging features
  - Main page styling

- **Arnav Mital (Scrummer 1)**
  - User login and logout functions
  - Profile customization

### Trio 2 - Product Page / Backend Development
- **Noah (Assistant Scrum Master)**
  - Kanban board management
  - Backend SQLAlchemy data definition and initialization

- **Jacob (Scrummer 2)**
  - AI integration for book recommendations
  - Book reviewing features and book database

- **Francis (Scrummer 3)**
  - Chat/discussion integration with backend data
  - Styling for a cozy book-themed discussion area
  - Programming and styling a page to announce upcoming books

## Next Steps

- [ ] **To-do 1:** Begin backend programming for data processing and chat functionality
- [ ] **To-do 2:** Start frontend programming for the main page and profile page

**Comment by gaheerab** [comment]
>Gaheera, Hannah, Rhea, Carson, Brandon, Rowan
> [Sprint 4 Planning Issue](https://github.com/gaheerab/gaheera_2025/issues/6)

**Comment by Kiruthic-Selvakumar** [comment]
[Sprint 4 Plan(Travel Theme)](https://github.com/Kiruthic-Selvakumar/travel_frontend/issues/1)
Per 1: Kiruthic, Tarun, Rohan, Arhaan, Aadi, Aaditya, Derek

**Comment by nikhilsna** [comment]
**Team FitConnect:**

[Sprint 4 Planning Issue](https://github.com/nikhilsna/sprint4_frontend/issues/1)

**Comment by SanPranav** [comment]
(Sprint 4 Planning Team Issue - Team Prism)[https://github.com/illuminati1618/prism_frontend/issues/2]

**Comment by illuminati1618** [comment]
[Sprint 4 Planning Team Issue - **Team Prism**](https://github.com/illuminati1618/prism_frontend/issues/2)

Group Members: Aditya Katre, Anvay Vahia, Mihir Bapat, Pranav Santhosh, Manas Goel, Yash Parikh

**Comment by JustinQ-DNHS** [comment]
[Sprint 4 Planning Team Issue](https://github.com/JustinQ-DNHS/justin_2025/issues/7)

Group Members: Justin Quach, Manahil Khan, Shriya Shah, Weston Gardner, Lars Andre Lindain, Rutvick Thavda, Shaurya Singh

**Comment by magic005** [comment]
[Sprint 4 Planning Issue - **Team Club Hub**](https://github.com/magic005/sprint4_frontend/issues/1)

Group Members: Ansh, Kush, Jonah, Ethan, Gyutae

**Comment by lalita1809** [comment]
Joanna, Bailey, Yuva, Nathan, Ahmad, Lalita: Group Members

https://github.com/lalita1809/lalita_2025/issues/6

**Comment by Tvick22** [comment]
https://github.com/Tvick22/personal_flocker_frontend/issues/1

Trevor, Wyatt, Jackson, Aarush, Gavin, Thomas, Kush

**Comment by RayhaanSheeraj** [comment]
https://github.com/RayhaanSheeraj/Sprint-4-CSP-Project-Frontend---Neil-Rayhaan-Hithin-Nikith-Zaid-Pradyun/issues/1

Team Members: Pradyun Gowda, Rayhaan Sheeraj, Neil Chandra, Hithin Pulamarasetty, Nikith Muralikrishnan, Zaid Alrefai

**Comment by Annie0523** [comment]
Sprint 4 planning issue https://github.com/Annie0523/sprint4_frontend/issues/1
